import changes from `dev' branch of rmottola/Arctic-Fox: - Bug 1198588 - Remove unused MSG-specific code from AudioStream. r=padenot (79bd29d60c) - Bug 1187195 - Remove all agents with null window. r=baku (c3733647bb) - Bug 1137151: Marked destructors of ref-counted audio-manager classes as protected, r=dhylands (d0b84530f6) - Bug 1179181 - Store separate volume setting into setting database. r=baku (a6cb4bab03) - Bug 1175447 - mono audio support. r=padenot, r=sotaro (ce011f6556) - Bug 1140763 - Build dom/media/gtest in unified mode; r=cpearce (b3061b094b) - Bug 1194442 - Code clean up of AudioManager r=alwu (d25f51cda2) - Bug 1137659 - Re-enable LogShake xpcshell tests on B2G Emulator debug. r=me (f8b037756a) - Bug 1136777 - Enable LogShake by default and listen for new content events. r=fabrice, r=gerard-majax (1cf207dbe8) - Bug 1101994 - Add a low-pass filter to LogShake's shake detection and refactor unit tests to be less redundant. r=mhenretty, r=gerard-majax (7f59e328ec) - Bug 1144499 - Consolidate two long-running tests in test_logshake_gonk into one test of equivalent strength. r=gerard-majax (765d0bc243) - Bug 1079763 - Compress logs produced by LogShake. r=gerard-majax (26e5ca1dec) - Bug 1181561 - Expose a Kill Switch enabling/disabling. r=dhylands, sr=sicking (03d2754eea) - Bug 1174682 - Rename logshake-screenshot to screenshot.png. r=gerard-majax (b6faaa3fc2) - Bug 1188999 - LogShake does not fetch about:memory reports. r=gerard-majax (03a75e6408) - let-var (1114e25a65) - Bug 1188487 - Add API to BrowserElement to mute and set volume. r=fabrice (3d49951639) - Bug 1195801 - Add GetStructuredData() method to Browser API. r=kanru, r=bholley (b4cc0cba61) - Bug 1167465 - Exposing Allowed Audio Channels in System App's Window, r=alwu, r=fabrice (e8d59eb0e1) - fix build (8a58b834fe) - Bug 1183301 - GetAllowedAudioChannels should not throw an exception if nsIFrameElement is not ready. r=baku (1adbb9b140) - Bug 1184821 - Use CheckAllPermissions in BrowserElement.webidl r=bz (65a22b5bc1) - Bug 1206212 - Remove AUDIO_STREAM_FM after KK r=alwu (4d83c541dc) - Bug 1131927 - [Automounter] Add reporter to get current information. r=dhylands (d5d2e94b8c) - Bug 1197689 - Avoid unnecessary sync IPC in AudioChannelManager ctor. r=baku (128abefeb6) - Bug 1208155 - Make hal functions explicit in AudioManager r=alwu (d320b83fa7) - Bug 1179691 - [Automounter] Fix the problem of get format and share request in the same time. r=dhylands (768ad35244) - Bug 1137151: Marked destructors of ref-counted auto-mounter classes as protected, r=dhylands (c8cf90bdff) - Bug 1158047 - [AutoMounter] Resolve the problem of stucking in UMS_CONFIGURING state. r=dhylands (793f023fd2) - Bug 1012403 - Reenable SettingsService chrome tests, on B2G only; a=TEST-ONLY (aa8c416f75) - Bug 1196358 - update volume setting to database when the volume changing. r=sotaro. (5227fca7f7) - let-var (ca6890c85b) - update (9b9ff0ca42) - Bug 1178081 - Make ro.product.manufacturer and ro.product.device available through settings. r=fabrice (fe962dfe41) - Bug 1206741 - [OTA] Make URL pref changes overwrite B2G's setting. r=fabrice f=gerard-majax (df8bf913ae) - Bug 1196884 - Disable device discovery (again) r=gerard-majax (9f11b3fa9d) - Bug 1178512 - [Metrics] Make the developer HUD send Advanced Telemetry events. r=janx (ddc3643e4e) - Bug 1177143 - Throttle HUD memory collection to 2 seconds. r=jryans (94fea375a8) - Bug 1190622 - [Telemetry] Report USS memory at time of performance marks r=jryans (fd7713fda0) - missing of Bug 1183101 - Collect Histogram Data from Gecko and send to Telemetry Server. r=janx (176b076539) - Bug 1176992 - Allow hud.js to support custom metrics with exponential and counter histograms. r=janx (c536b35be1) - Bug 1198517 - [Metrics] Histogram support for user-timing-based metrics. r=janx (549741a1e4) - Bug 1180793 - [Metrics] Hud should report specific app for those Apps housed under 'Communications'. r=janx (93407f1873) - Bug 1189871 - Add event to add/remove permissions for Graphene. r=fabrice (004144b5ba) - let-var (8c98d39873) - Bug 1160923 - [B2G] Waiting for explicit mozContentEvent before sending out mozChromeEvents, r=vingtetun, f=ochaumeau (63fc3b5ea8) - missing bits of 1177143 and cleanup (339e589ba1) - Bug 1188762 - Use mozSystemWindowChromeEvent to instead of mozChromeEvent to send system-audiochannel-state-changed event. r=alwu (d107f0caab) - Bug 1192122 - Safe mode startup, Part 1: check the power key state at startup r=mwu (90af9b56c0) - Bug 1192122 - Safe mode startup, Part 2: shell.js hook r=ferjm (02676818ff) - Bug 1156715 - Create shell-remote for launching system-remote, r=fabrice (43b18841c9) - missing of Bug 973933 - New updater-xpcshell binary for updater tests. (e6f8cd734a) - Bug 1178760: Add ability to read ua-update.json from APK for Fennec. r=jchen (649d110fdf) - bits of Bug 1076314 - Re-prompt nightly users to enable e10s. (5530f26d51) - Bug 1167601 - Convert newTab.xul to newTab.xhtml. r=mconley (659c19a586) - Bug 1040369 - Replace sponsored icon with identifying text [r=adw] (6ce29de713) - Bug 1192924: Expose the update URL formatting code a new UpdateUtils module. r=rstrong (f2bc4ba6a7) - some of the newer icons (bf3c415d72) - various cleanup and missing bits of Backed out changeset 84da123a0af0 (bug 895359) (d7feb9e535) - bits of Bug 1158853 (02223f32ee) - Bug 1196437 - Moving a sponsored tile in newtab breaks various things [r=marcosc] (0c93d54931) - Bug 1203787: When the add-on ID is longer than 64 characters compare the signing certificate's common name to the sha256 hash of the ID. r=dveditz (838d6ce69c) - bits of Bug 1036284 - Update styling of newtab tiles (886f7d2b71) - let-var (e0ed7d020c) - bug 890026 - Add mozcrash.kill_and_get_minidump r=jimm (11fe69e302) - Bug 1162115 - Bump mozdevice to 0.45, r=wlach (4b5891b54e) - Bug 1140145 - Update to latest wptrunner, a=testonly (a7860252bd) - Bug 1146321 - Update to latest wptrunner, a=testonly (c81ea8eddd) -  Bug 115107 - Update to version of wptrunner that allows prefs to be set, r=Ms2ger, ahal (972f8c55bd) - Bug 1154691 - Update wptrunner to remove old exception type, a=testonly (f96ce919b1) - Bug 1150821 - Update to latest wptrunner, a=testonly (bea754f26c) - Bug 1153521 - Update to latest wptrunner, a=testonly (830e395995) -  Bug 1155079 -Update to latest wptrunner, a=testonly (27cfd9c8a5) - Bug 1163709 - Update to latest wptrunner, a=testonly (76672ace86) - Bug 1160085 - Update to latest wptrunner, a=testonly (168e165a26) - Bug 1157218 - Update to latest wptrunner, a=testonly (d9eabd0213) - Bug 1171755 - Update to latest wptrunner, a=testonly (4f5b411410) -  Bug 1139407 - [mozversion] Remove non-text formatters from command line log options. r=dhunt (32f7596553) - Bug 1160087 - [moznetwork] Add command line interface. r=wlach (2efccde362) - Bug 1175101 - [moznetwork] Bump version number to 0.25. r=wlachance (c8a0fa9ff2) - Bug 1176677 - [moznetwork] ImportError: "cannot import name structured", and release version 0.26. r=davehunt (009449ec79) - Bug 1160090 - [moznetwork] Add structured logging. r=wlach (05a7bc26bc) - Bug 1160094 - [moznetwork] Attempt to pick most suitable IP when multiple are associated with the hostname. r=wlach (db464651e1) - Bug 1163992 - [moznetwork] When multiple IPs are found on Windows pick the first one. r=wlachance (88207df55a) - Bug 1146292 - [mozlog] Bump version to 2.11. r=jgraham (3f9e252ac4) - Bug 1171032 - Log raw messages at debug level by default, r=chmanchester (1ac8fa11ff) -  Bg 1171849 Let consumers override mozlog default formatter options, r=chmanchester (beb37921ca) - Bug 1066643 - [mozlog] Allow users of mozlog's command line options to exclude inappropriate log types. r=jgraham (8f4758a6c0) - Bug 1132409 - [mozlog] Create directories for log specified on the command line if not present. r=jgraham (2bda47bd25) - Bug 1177630 - Add formatter to mozlog for producing a machine readable error summary, r=chmanchester (a5930babb0) - Bug 1173380 - [mozprofile] cloned profiles are not cleaned (__del__ method is not called); r=ahal (9d7d931dbf) - Bug 1173682 - [mozbase] tests do not remove created directories; r=ahal (a4b3c112ab) - Bug 1161198 - Update mozdevice test for getLogcat; r=bc (10be1b1a85) - Bug 1014760 - Move mozlog.structured to mozlog; Move mozlog to mozlog.unstructured, r=jgraham (8c1eba0f64) - Bug 1176408 - Bump marionette-transport to 0.5 and marionette-driver to 0.9, r=dburns (fae313803a) - Bug 1178778 - Bump marionette-driver to 0.10. r=automatedtester DONTBUILD (4196568a38) - Bug 1183157 - make marionette --version flag also show the transport and driver package versions. r=dburns (e068536c58) - Bug 1189027: Bump marionette driver to 0.11; r=ato (b1d103c9ef) - Bug 1188826: Bump marionette client version for release; r=ato (018809aae3) - Bug 1176882 - Don't pin marionette-transport. r=davehunt (c660f3ab7b) - Bug 1169381 - Bump dependency for mozinfo in marionette-client to >=0.8. r=jgriffin (a6c0edc9bf) - Bug 1190817 - marionette install from pypi is broken. r=automatedtester (c43fbcfaee) - Bug 1163801 - Upgrade marionette-client from optparse to argparse, r=ahal (5843864209) - Bug 1163801 - Refactor marionette's options mixin system for argparse compatibility, r=AutomatedTester (c8153ebde4) - Bug 1197835 - Version bump marionette-client == 0.19, marionette-transport == 0.7, marionette-driver == 0.13, r=ato (4d7a79ae9a) - Bug 1200973 - Remove unneeded app cache code from Marionette; r=jgriffin (0c2792e2a5) - Bug 1194923 - Call glFlush before glDeleteFramebuffers on Adreno 420 devices. r=snorp (cc1597d3f1) - Bug 1150668 - Assume EXT_texture_format_BGRA8888 supported on Android emulator; r=jgilbert (d6e1884d28) - Bug 1140459 - Skip IsRenderbuffer assertions on Android emulator; r=jgilbert (2163e7c66b) - Bug 683218 - Disable __noSuchMethod__ support. r=jorendorff (b00cc0c8ae) - Bug 1206168 - Rename JS_DefaultValue to JS::ToPrimitive. r=jandem. (0815b56474) - pointer style (d5a0b0f1cc) - Bug 1133191 - Part 0: Add indentation variant to JS::BuildStackString. r=jandem (2383f33b84) - Bug 1133191 - Part 1: Display JS stack trace on exception in js shell. r=jandem,jorendorff (5000cb3ec8) - fix patch order (a84ffb1d33)