import changes from `dev' branch of rmottola/Arctic-Fox: - Bug 1173260 - stub out tests that fail when 'cursive' is looked up via fontconfig. r=m_kato (0bb3f03cb8) - bug 1215657 - make AccessibleWrap::get_accDefaultAction work with proxied accessibles r=davidb (5732eb38eb) - Bug 1210549 - Allow IServiceProvider::QueryService to work for proxied accessibles r=tbsaunde (7dcd9c2271) - bug 1215657 - make AccessibleWrap::accSelect work with proxies r=davidb (d52e3d4873) - Bug 1212297 - improve error handling in Chrome bookmarks migration code, r=MattN (b6c727ccdf) - Bug 1236551 - Update tests to cover Telemetry profile migrator. r=MattN (6f05af5c3c) - Bug 1246591 - fix whitespace issues, r=MattN (dd7e7474c1) - Bug 1225682 - Don't use nsAuto{,C}String as class member variables in rdf/. r=Pike (f681938445) - Bug 1232454 - use UniquePtr<T[]> instead of nsAutoArrayPtr<T> in security/apps/; r=keeler (e416936ed6) - Bug 1235796 - Allow allocating YCbCr textures with Cb/Cr planes bigger than the Y plane. r=jrmuizel (8f1dbe137c) - Bug 1241816 - In CreateSourceSurfaceFromMacIOSurface, unlock the IOSurface even in failure cases. r=mattwoodrow (218e6da6c1) - Bug 1240190 - Add D3D9 texture upload profiler labels. r=jrmuizel (1e55b77bdf) - Bug 1213429 - Recycle e10s D3D9 textures and add partial upload support. r=Bas (97aeeefdd2) - Bug 1213429 - Check the result of LockRect. r=Bas (1c3c981d80) - Bug 1213429 - GCC compilation fixup. (5449005c99) - Lazily initialize D3D11 mix-blend shaders. (bug 1246388, r=mattwoodrow) (6fd3226030) - Bug 1237375: Add some more extensive debugging information. r=milan (aed95e4774) - Bug 1239861. Part 2 Properly resize DXGI swap chain buffer size. r=bas (e9bf410de4) - Bug 1247775 - Part 1: Remove D3D10/D2D 1.0 texture integration from layers. r=dvander (74d7e93792) - Bug 1247775 - Part 2: Remove Direct2D 1.0 code from Thebes. r=dvander (f0a1f53917) - Bug 1247775 - Part 3: Remove Moz2D code to support Direct2D 1.0. r=dvander (10d27128eb) - Bug 1221656 - Copy mp4parse.h in update-rust.sh. r=kinetik (96ebce3eb8) - Bug 1238420 - Update mp4parse-rust to 0.1.6. r=kinetik (ed3fff21e6) - Bug 1215234 - Update to byteorder v0.3.13. r=kinetik (3481fa0015) - Bug 1219452 - Fix unused attribute warning. r=kinetik (4962dc944f) - Bug 1238420 - Update byteorder to v0.4.2. r=kinetik (c46dbda1bf) - Bug 1243234 - Move mp4parse into a crate subdirectory. r=kinetik (a2b69f5af8) - Bug 1243234 - Update script for mp4parse v0.2.1. r=kinetik (3c1c1f0a1b) - Bug 868333 - Match more MP4 family file types in media sniffer. r=rillian (cd29bd2a74) - Bug 1211802 - Recognize 'avc?' as mp4 video. r=jya (b68726705b) - Bug 1244523: [mp4] P2. Have sniffer recognise ftyp qt subtype. r=cpearce (1770f0862b) - Bug 1246591 - remove preprocessing and fix any other issues, r=MattN (7f9657c2eb) - Bug 1200187 - Failed to compile nsEdgeReadingListExtractor.cpp: error C2664: cannot convert argument from 'char16_t *' to 'JET_PCWSTR'. (e9bf07b5ca) - Bug 1200656 - Reading list import from Edge leaks. r=jimm (6a30ceca89) - Bug 1200656 - followup, use char16ptr_t to fix builds with VS 2015. r=mak (14a8890583) - Bug 1207100 - Fixed nsEdgeReadingListExtractor.cpp compilation on GCC. r=Gijs (fe197532b9) - Bug 1218315 - Replace NS_LITERAL_STRING(...).get() with MOZ_UTF16(...) on browser. r=nfroyd (a4cc3cd9d9) - Bug 1225798 - part 1: add better error reporting for reading list importer's ESE handling, r=MattN (43bc443429) - Bug 1225798 - part 2: move reading list import to its own bookmarks migrator source, r=MattN (dd979ad08e) - Bug 1228482 - Fix compile error with VS2015 and memory leak in nsEdgeReadingListExtractor. r=bas (07f77c9cb3) - Bug 1228482 - use nsAutoString instead of handling raw strings, r=gijs (fd6d8bd3ad) - Bug 1229076 - use JS module for reading ESE database, r=MattN (ebc8d1ba58) - Bug 1246591 - fix moz.build file and .eslintignore, r=MattN (d320bceec6) - Bug 1087488: Remove some SPROP macro usages in Omnijar.cpp, to avoid triggering -Wtautological-compare clang warning. r=glandium (697dfa9895) - Bug 1228437 - Add BHR stats from e10s child process. B2G fix by Ting-Yu Chou. r=nchen (213fbb9f37) - Bug 1198196 - rework EVENTLOOP_UI_LAG_EXP_MS to record all lag. r=vladan (2807460ce0) - Bug 1240484 - fixed control flow patch issue by adding brackets. r=mccr8 (d2aac14ee1) - Bug 1242119 - Remove early exit in WinXP debug content processes. r=froydnj (2c2626a1ea) - Bug 1245513 - Use _exit(0) to exit in B2G debug content processes. r=froydnj (c37efd34d9) - some crash and profiler stuff (87547f6d8f) - bug 1234417 - fix a leak in CreateECPublicKey r=rbarnes (99848f0fae) - Bug 1204784: Handle cases in nsThreadPool where Gecko doesn't own the thread that we're running on. r=froydnj (3f523fc544) - Bug 1204784: Do not shut the main thread down before all outstanding asynchronous thread shutdowns complete. r=froydnj (6abfb2562f) - Bug 1234126 - Add Chaos Mode support for setting thread affinity on OS X and Windows. r=froydnj (8811430596) - Bug 1245586 - add debugging aids for thread shutdown; r=khuey (28b7ae88c3) - Bug 1191936 - Implement SPKI/PKCS#8/JWK import/export for RSA-PSS r=rbarnes (212ab7fec5) - Bug 1241757 - Permit export of JWK with empty key_ops field, r=rbarnes (b19f177a13) - Bug 1205168 - Part 0: Remove copy-ctor from strong type. r=jgilbert (a6070322a1) - Bug 1205168 - Part 1 - Sort all the WebGLTexelFormats. r=jgilbert (857cd58641) - Bug 1205168 - Part 2: Texel Conversion - RG8 format. r=jgilbert (6c241194ed) - Bug 1205168 - Part 3: Texel Conversion - RG16F format. r=jgilbert (7573635218) - Bug 1205168 - Part 4: Texel Conversion - RG32F format. r=jgilbert (f54343317e) - Bug 1205168 - Part 5: Texel Conversion - RGB11F11F10F format. r=jgilbert (500514e025) - Bug 1205168 - Part 6: Fix TexImage2D and TexSubImage2D with texture conversion. r=jgilbert (b5e2e75276) - Bug 1205168 - Part 7: Remove unneeded functions. r=jgilbert (9bd24cd813) - Bug 1234744 - Fix build errors in ImageBitmap.h. r=roc (b4b67e5905) - missing telemetry bits (28161fd3f9) - Bug 1237193 - Fix WebGL getActiveUniforms return type. r=jgilbert, r=smaug (f9a37a360e) - Bug 1233353 - Initialize rb correctly if rb bind to READ_FRAMEBUFFER. r=jgilbert (bbc77437a4) - Bug 1237637 - Disallow negative levels for framebuffer attachments. -r=jrmuizel (fa65b6ad24) - Bug 1236395 - [WebGL2] pass getFramebufferAttachmentParameter in gl-object-get-calls.html, r=jgilbert (6f9fde1cd2) - Bug 1236784 - [WebGL2] pass getRenderbufferParameter in gl-object-get-calls.html, r=jgilbert (e4f20f54ad) - Bug 1238865 - Part 1: Validate attachments before clearBuffer. r=jgilbert (a6e6e05a0c) - Bug 1229210. Handle the new formats required by WebGL2 in ReadPixels. r=jgilbert (66e305f97d) - Bug 1238865 - Part 2: Add more format/type checks for WebGL2. r=jgilbert (af629782b3) - Bug 1238865 - Part 3: Prevent IMPLEMENTATION_COLOR_READ_FORMAT return SRGB_ALPHA. r=jgilbert (81da93d791) - Bug 1240673 - Fix WebGL2 framebuffer parameter problem. r=jgilbert (2c957a8294) - Bug 1240438 - Fix WebGL2 framebuffer attachment related implementation. r=jgilbert (b4339241c8) - Bug 1239187 - Use the GLFeature instead. - r=jrmuizel (c5f2c57646) - Bug 1094458 - Implement RenderbufferStorageMultisample. - r=jrmuizel (f20f776597) - Bug 1246007 - Ignore RENDERBUFFER_SAMPLES outside of webgl2. - r=jrmuizel (6b8f59ae49) - Bug 1243907 - Don't query _BITS enums on Core profiles. - r=jrmuizel (e722abe45b) - partial Bug 1242120 - Remove switch fallthrough (0f47fb7a71) - Bug 1236080. Null check format in GetParameter. r=jgilbert (09fedc2ea8) - Bug 1240662 - Add max level check for framebufferTextureLayer. r=jgilbert (f6d5eda15c) - Bug 1236091. Move validate checks inside of null checks. r=jgilbert (4c67e04e87) - Bug 1237191 - Add check for getQueryParameter to return correct error. r=jgilbert (93345aab7e) - Bug 1230089 - If sampler is bound, use parameter of sampler. r=jgilbert (e4139a5174) - Bug 1242336 - Fix WebGL2 return type of GL_UNPACK_SKIP. r=jgilbert (4a2ef1956e) - Bug 1240262 - Annotate intentional switch fallthrough and suppress -Wimplicit-fallthrough warnings in dom/canvas/. r=jgilbert (eaee57ba8f) - Bug 1237194 - Fix getSyncParameter return error. r=jgilbert (13119be06e) - Bug 1239541 - Fix WebGL2 texImage related checking. r=jgilbert (6777244db0) - Bug 1225291 - IsTransformFeedback doesn't report error when input is null. r=jgilbert (8c67d072b5) - Bug 1233094. Handle null buffers in GetIndexedParameter. r=jgilbert (ae5d75bd47) - Bug 1228676 - WebGL2 VertexAttrib funcs should match WebGL 1 patterns. - r=jgilbert (bf96c0e17b) - Bug 1237420 - "Fix length-checking when setting WebGL 2 vertex attributes with an array". r=jgilbert (d8e9ca7111) - Bug 1233819 - Fix WebGL on WinXP. - r=jrmuizel (39b15ba9ee) - Bug 1233046 - Mark non-try platforms. Align some tests. (9d16ce70a4) - Bug 1201885,1247752,1247753 - Re-mark passing/failing tests. (381c71c0f8) - Bug 1247764 - Disable STENCIL_TEST on mac+intel when not needed. - r=jrmuizel (0b544d0c36) - Bug 1243908 - Use DrawBuffers through GLScreenBuffer when operating on fb0. - r=jrmuizel (0ac0fc6047) - Bug 1229944 - Add glClear for zeroing texture data. - r=kamidphish (51df8cbb50) - Bug 1220450 - Clear length on cache OOM. r=kamidphish (44431a0d3e) - Bug 1232346 - Clarify ResolveForDraw's failure checking. - r=kamidphish (542917bb85) - Bug 1229076 - Follow-up to remove leftover component references for the C++ Edge Reading List Migrator. r=bustage (f18952b8f7)