import changes from `dev' branch of rmottola/Arctic-Fox: - Bug 1153148 - Add documentation comment for JSOP_SUPERBASE and JSOP_INITHOMEOBJECT. r=efaust (b6ecd21e1) - Bug 1153057 - Properly initialize the [[HomeObject]] of methods with computed property names. (r=jorendorff) (6c2226674) - Bug 1152304 - Record the end of block scope notes to be after emission of JSOP_POPBLOCKSCOPE. (r=jimb) (295502f81) - Pointer style (7f3f22ce3) - Bug 1155466 - Freshened blocks should pop their old blocks in debug scopes. (r=Waldo) (359fff80b) - pointer style (107fb5b95) - Bug 1156190 - Do not emit DEBUGLEAVESCOPE if we're also going to emit POPBLOCKSCOPE. (r=jimb) (af5fde7ef) - cleanup (292b5baa7) - do not inline (cc14b6170) - pointer style (637cc4e01) - pointer style (e203a150f) - Bug 1149498 - Watch for preliminary object groups in more places, r=jandem. (a623a2d06) - Bug 1155946 part 1 - Add a mayResolve class hook to optimize objects with resolve hooks better. r=bhackett (e45ebda33) - Bug 1155946 part 2. Add mayResolve methods to DOM classes with resolve hooks. r=peterv (9efb0c070) - pointer style (d0c09e4ec) - Bug 1149119 - Use Atoms in the template object hold by Baseline. r=jandem (63fe170e9) - Bug 1149119 - Do not inline bound functions with non-atomized arguments. r=jandem (facc9cb06) - Bug 1155807 - Watch for converted native groups with unknown properties, r=jandem. (257e11ff3) - Bug 1136584 - Fix warning-as-errors error. r=me (11768280a) - pointer style (f2234b36f) - Bug 1157809 - Optimizing scanning of unboxed plain objects and typed objects during nursery collections, r=terrence. (f37855a60) - Bug 1153266 - Allow turning on unboxed objects with an environment variable, r=h4writer. (504984da7) - Bug 1145426 - Fix compilation of unboxed object construction stubs on ARM and x86, r=jandem. (be1491b56) - Bug 1145795 - Remove LJSCallInstructionHelper::numStackArgs() footgun. (r=jandem) (c3e952856) - Bug 1147629 - Use getStackPointer() and helper functions. r=jandem (97d6b4054) - Bug 1147608 - Fixes for unboxed object creation stub compilation on x86 and ARM, r=jandem. (abc526773) - Bug 1146363: Inline SIMD.int32x4.bool; r=sunfish (d655dc72e) - Bug 1155793 part 1. Make it possible to safely change the number of bits in the slotIndex field in jitinfo. r=efaust (c6124396d) - Bug 1155793 part 2. Split apart the concepts of movability and eliminatability in jitinfo, since some things are not movable but are eliminatable. r=efaust (848b751b8) - Bug 1135040: Optimize SIMD shifts in Ion; r=nbp (a61b8ae26) - pointer style (b9921d90f) - rearrange (38c9a7c33) - Bug 1142668: Fix int32x4 to float32x4 conversions in the JIT; r=sunfish (6f3ac7a59) - pointer style (29df6bf54) - pointer style (bebd7f1d6) - Bug 1134198 - Refactor JS_GENERATOR_CLOSED checking. (r=jandem) (55c3062dd) - Bug 1134198 - Rename assertNotInFrameMaps to inFrameMaps. (r=tromey) (e8a8ecfff) - Bug 1134198 - Update tests to reflect new specced behavior on Debugger.Frame.onPop. (r=tromey) (8126f8ecf) - Bug 1134198 - Update docs for new Debugger.Frame.onPop spec. (r=tromey) (7520665c1) - Bug 1134198 - Fix up tests now that onPop and onExceptionUnwind may be called at different locations than previously. (r=tromey) (6651e74b7) - Bug 1134198 - Don't call Debugger::slowPathOnLeaveFrame on frames no longer in Debugger frame maps. (r=jimb) (a8856ece8) - Bug 1134198 - Call Debugger::onPop at the point that caused the frame to pop before any unwinding in the interpreter. (r=jimb) (84a4f3f70) - pointer style and cleanup (5bc4c3114) - no bug - fix windows includes for case sensitive file systems (48835fd8b) - pointer style (ef70bfbcb) - pointer style (f739ba488) - pointer style (1cc9808f8) - Bug 1146597 - Add unboxed arrays for JSOP_NEWARRAY arrays, and shell option for using them, r=jandem. (d7b424fc3) - pointer style (5877eb088) - Bug 1157703 - Cache iterators involving unboxed objects, r=jandem. (f2670a817) - pointer style (bfbb868b7) - Bug 1146597 - Remove redundant check for unboxed object/array runtime option. (3b533c202) - Pointer style (1984bb1e8) - pointer style (6fbaea70a) - Bug 1142828 - Refactor to avoid having [[Set]]-specific weird cases in the [[DefineOwnProperty]] code. r=Waldo. (4661cdecb) - Bug 1147660, part 1 - Refactor NativeDefineProperty to put DefinePropertyOrElement's only call site right at the end. No change in behavior. r=efaust. (824cb5e2b) - Bug 1147660, part 2 - Merge DefinePropertyOrElement into NativeDefineProperty, making one long function we can refactor. r=efaust. (89a6bf7e0) - Bug 1147660, part 3 - Rearrange NativeDefineProperty so that special cases are all dispensed with, and ES6 checks done, by the time we start thinking about how to update the object. r=efaust. (b0234d161) - Bug 1147660, part 4 - Change NativeDefineProperty to use a PropertyDescriptor internally instead of a bunch of variables. This is a little ugly at first but it'll get better. r=efaust. (1c1999a57) - Bug 1147660, part 5 - Split the part of NativeDefineProperty that updates the object into a separate function again. r=efaust. (5dc0316b5) - pointer style (f66459369) - Bug 1148652, part 1 - Move array-specific special cases to the top of NativeDefineProperty; update ArraySetLength to be able to cope with incomplete attrs. r=efaust. (e2dca6628) - Bug 1148652, part 2 - Use mostly-compliant code for defining TypedArray elements, already used from StandardDefineProperty, in NativeDefineProperty as well. r=efaust. (b5e8489ed) - Bug 1148652, part 3 - Mark arguments.length as overridden when it is redefined via the C API. r=efaust. (0f44925f1) - Bug 1148750, part 1 - Factor out the lookup common to three branches at the top of NativeDefineProperty. r=efaust. (b9e4e7254) - Bug 1148750, part 2 - Check extensibility in NativeDefineProperty. r=efaust. (202f4e12e) - Bug 1148750, part 3 - Implement ValidateAndApplyPropertyDescriptor step 2. r=efaust. (acb6afa35) - Bug 1148750, part 4 - Strip out redundant if-conditions in parts of NativeDefineProperty where shape can't be null. r=efaust. (15d24b5f4) - Bug 1148750, part 5 - CompletePropertyDescriptor upgrade. r=efaust. (69bd74ce3) - Bug 1148750, part 6 - Implement ValidateAndApplyPropertyDescriptor up to step 5. r=efaust. (94aef08b5) - Bug 1148750, part 7 - Fill in configurable and enumerable. r=efaust. (698bfa16d) - Bug 1148750, part 8 - Implement ValidateAndApplyPropertyDescriptor step 6. r=efaust. (7459d31ba) - Bug 1148750, part 9 - Implement ValidateAndApplyPropertyDescriptor step 7. r=efaust. (9593b3312) - Bug 1148750, part 10 - js::NativeDefineProperty: Swap the order of the cases in the remaining old code. r=efaust. (90a61b163) - Bug 1148750, part 11 - Remove some code for TypedArray cases rendered unreachable by part 1 of this bug. r=efaust. (d57f75b20) - Bug 1148750, part 12 - Reject redefinition of non-writable non-configurable data property as writable. This fixes bug 1073808. r=efaust. (d1783a786) - Bug 1148750, part 13 - Simplify code to fill in desc.writable, if not present, from the existing shape. r=efaust. (aa01780a6) - Bug 895223 - Use JSNative instead of JSGetterOp for ctypes FieldGetter/Setter. r=jorendorff (01372b866) - Bug 895223 - Always pass the holder to JSGetterOps. r=jorendorff,jandem (62bff004b) - Bug 895223 - Test for the now correctly behaving properties (e.g array.length). r=jorendorff (5238a0c44) - Bug 1153651 - Define array.length as JSPROP_SHADOWABLE. r=jorendorff (6645ed732) - Bug 1149563 - Change bogus ctypes code that modifies a frozen object. r=efaust. (1777ad24d) - Bug 1148750, part 14 - Reject redefining a non-writable non-configurable data property to have a different value. r=efaust. (a2e81df42) - Bug 1148750, part 15 - Stop retaining getter and setter ops when redefining a data property. r=efaust. (1c6f67821) - Bug 1148750, part 16 - Implement ValidateAndApplyPropertyDescriptor step 9 (redefining an existing accessor property). Remove CheckAccessorRedefinition. r=efaust. (0affd1437) - pointer style (0697799b8) - Bug 1153475 - Always ignore desc.object() in DefineProperty functions that take a PropertyDescriptor argument. r=efaust. (d9615554e) - pointer style (f883227a9) - Bug 1147005 - Change JSAddPropertyOp signature. r=jorendorff,peterv (83530a9b4) - Bug 1125567 - Remove FindClassPrototype/FindClassObject. r=jorendorff (f89fd6b99) - Bug 1125302 - Remove NativeLookupProperty. r=luke (b6dc7bac8) - Bug 1062473: Add 'const' qualifiers to this for some NativeObject methods and free functions. r=terrence (7e4cc56cd) - Bug 1062473: Add 'pointer-byte-size' to getBuildConfiguration results. r=sfink (93edbaca6) - pointer style (ff234eb8b) - Bug 1155197: For JS::ubi::Node, provide jsObjectClassName directly in JSObject specialization. r=terrence (9151ceb5f) - Bug 1062473: Make JSObject::allocKindForTenure out of GetObjectAllocKindForCopy. r=terrence (9575ad90e) - Bug 1062473: Implement JS::ubi::Node::size for JSObjects. r=sfink,terrence (aeacda1ca) - Bug 1160986 - Update Histograms.json for RegExp#source access (followup for bug 1153963). r=gfritzsche (9defab499) -  Bug 1154296 - Small GetOwnPropertyDescriptor cleanup. r=jorendorff (fef8fb35e) - Bug 1134865 - Part 1: Add JSObject::constructorDisplayAtom; r=djvj (db97321c4) - pointer style (f237fad9c) - Bug 1154079 - Add the allocated object's [[class]] name to the allocations log. r=shu (d5bab15fa) - Bug 1134865 - Part 2: Add constructor name to the allocations log; r=djvj (c11125323) - Bug 1063257: Implement JS::ubi::Node::size for JSString. r=sfink (491b25b28) - Bug 1134865 - Part 3: Add JS::ubi::Node::jsObjectConstructorName; r=djvj (dd74ed300) - Bug 1158463 - Reorder property creation in js::FromPropertyDescriptorToObject. r=Waldo (afb9f302d) - Bug 1161077 - Allocate unboxed arrays in the nursery, r=terrence. (df198da45) - Bug 1159806 - Replace macro assertions with inline functions; r=sfink (c493b7a83) - Bug 1161353 - Remove the post-barrier verifier; r=sfink (3c64f8b44) - pointer style (0f1785941) - Bug 1148921 - Check correctness of hash table modifications later on during minor GCs, r=jonco. (6f8cf20b0) - Bug 1158569 - Don't trigger sweeping of dead type information when scanning unboxed objects in minor GCs, r=terrence. (7d5c9d20d) - Bug 1161726 - Use a custom tracer for tenuring to avoid the indirect calls; r=jonco (f2088e2ae) - Bug 1161353 - Follow-up to remove more post-barrier verifier cruft; r=terrence (903a81bd5) - Bug 1160887 - Fix various unboxed object bugs, r=jandem,terrence. (a7aca9fc9) - Bug 1161762 - Fix test used for whether an unboxed object layout is too large, r=jandem. (772157822) - Bug 1161346 - Add missing capacity for unboxed arrays, r=jandem. (9810cbf73) - Bug 1163810 - Use type-based dispatch for IncrementalReferenceBarrier; r=jonco (caf1273bd) - Bug 1162301 - Move tenuring implementation to TenuringTracer; r=sfink (5e51a3341) - Bug 1162303 - Simplify TenuringTracer's implementation; r=jonco (813446aa1) - fix order (15279b7ed) - Bug 1163643 - Fix unified build errors following recent marking changes r=terrence (83fe5b47a) - Bug 1161664 - Stay inline when visiting the WholeObject store buffer; r=sfink (d5efe7867) - Bug 1112627: Implement shift count saturation; r=Waldo (4f82dcabd) - Bug 1112627: Remove redundant inline specifier in SIMD operators impl; r=Waldo (0e6f1a31b) - Bug 1063946 SIMD: Group tests in logical units - conversions; r=bbouvier (35930b52c) - Bug 1155081 - Part 12: Replace ThrowError(JSMSG_TYPEDOBJECT_ARRAYTYPE_BAD_ARGS) with ThrowTypeError(JSMSG_TYPEDOBJECT_BAD_ARGS) in TypedObject.js. r=till (01152b406) - Bug 1155081 - Part 1: Replace ThrowError with ThrowTypeError in Array.js. r=till (002a1f3b9) - Bug 1155081 - Part 2: Replace ThrowError with ThrowTypeError in Error.js. r=till (4a76cc576) - Bug 1155081 - Part 3: Replace ThrowError with ThrowTypeError in Generator.js. r=till (08f8d6ae1) - Bug 1155081 - Part 4: Replace ThrowError with ThrowTypeError/ThrowRangeError in Intl.js. r=till (978326c2d) - Bug 1155081 - Part 5: Replace ThrowError with ThrowTypeError in Map.j…s/Set.js/WeakSet.js. r=till (217998d56) - Bug 1155081 - Part 6: Replace ThrowError with ThrowTypeError in Object.js. r=till (1c0e15e13) - Bug 1155081 - Part 7: Replace ThrowError with ThrowTypeError in RegExp.js. r=till (d23d58be8) - Bug 1155081 - Part 8: Replace ThrowError with ThrowTypeError/ThrowRangeError in String.js. r=till (c80fa9060) -  Bug 1155081 - Part 9: Replace ThrowError with ThrowTypeError in TypedArray.js. r=till (8311344de) - Bug 1155081 - Part 10: Replace ThrowError for TypeError with ThrowTypeError in TypedObject.js. r=till (44cee08bb) - Bug 1145058 - Annotate the SpeciesConstructor utility function with step-by-step comment numbering to make clear where we do (and do not!) follow the spec. Also fix issues related to our half-pretense of implementing this method without having first implemented the well-known @@species symbol. r=efaust (c0c60afe1) - Bug 1154532 - Add ThrowRangeError and ThrowTypeError intrinsics to make self-hosted code's behavior clearer -- and also have each assert that error number and requested error type are consistent. (It appears no self-hosted code throws SyntaxError, ReferenceError, or URIError yet, so no adding functions for those yet.) r=till (12b2f552f) - Bug 1155081 - Part 11: Replace ThrowError with ThrowTypeError in Utilities.js. r=till (b06c0c6d9) - Bug 1154542 - Remove a few unused error messages. r=till (f0248f8cd) - Bug 1147214 - Allow app: urls to use sw. r=baku (e3e1c02f5) - Bug 1099149 - Part 2: Add a more specific error message when 'js::ToSimdConstant' argument is of wrong type. r=bbouvier (3281bf2d6) - Bug 1161628 - Fix leak in ErrorWrongTypeArg. r=bbouvier (7e9c0f5f9) - Bug 1146718 - Split the 'J' tag in the profiler into 'J' (JIT frames without opt info) and 'O' (with opt info). (r=djvj) (d5ab6dff8) - Bug 1137569 - Stream and save samples and markers in the profiler on JSRuntime destruction. (r=mstange) (b1a6b9a7f) - Pointer style (67b999b2b) - Bug 1137569 - Delay stringification of JIT frames until streaming time. (r=djvj) (78d743512) - pointer style (716a0f543) - Bug 1140180 - Stop leaking TypeLists when tracking optimizations. (r=djvj) (cda2fe426) - Bug 1147224 - Only keep the optimization information of the last time IonBuilder visits a bytecode location. (r=djvj) (ad93a60b3) - pointer style (d29b2ac28) - Bug 1150714 - Fix streaming tracked optimizations for functions that don't have a displayAtom. (r=djvj) (c38845397) - pointer style (073a0adf4) - Bug 1150714 - Mark and sweep JitcodeGlobalMap IC entries. (r=djvj) (e9fe3dc34)