gre/modules/devtools/qrcode/decoder/index.js
JavaScript strict warning:
resource://gre/modules/devtools/qrcode/decoder/index.js, line 978:
SyntaxError: redefining eval is deprecated
JavaScript strict warning:
resource://gre/modules/devtools/qrcode/decoder/index.js, line 22:
ReferenceError: assignment to undeclared variable GridSampler
JavaScript strict warning:
resource://gre/modules/devtools/qrcode/decoder/index.js, line 836:
ReferenceError: assignment to undeclared variable DataMask
JavaScript strict warning:
resource://gre/modules/devtools/qrcode/decoder/index.js, line 1306:
ReferenceError: assignment to undeclared variable Decoder
https://bugzilla.mozilla.org/show_bug.cgi?id=1152836 (partially)
https://bugzilla.mozilla.org/show_bug.cgi?id=1202902 (partially)