[UXP task] gre/modules/commonjs/sdk/lang/weak-set.js
JavaScript strict warning:
resource://gre/modules/commonjs/sdk/lang/weak-set.js, line 9:
SyntaxError: 'use strict' statement won't be enforced as a directive
because it isn't in directive prologue position